---

- name: exist check /usr/local/client_golang/examples/random/random
  stat: path=/usr/local/client_golang/examples/random/random
  register: is_file_random

- name: git clone prometheus_client_git_url
  git:
    repo={{ prometheus_client_git_url }}
    dest=/usr/local/{{ prometheus_client_name }}
  when: not is_file_random.stat.exists

- name: build prometheus_client_golang
  shell: /bin/bash -lc "cd /usr/local/client_golang/examples/random;{{ item }}"
  with_items:
    - go get -d
    - go build
  when: not is_file_random.stat.exists
