---

- name: tar -zxvf https://github.com/prometheus/prometheus/releases/download/0.20.0/prometheus-0.20.0.linux-amd64.tar.gz -C /usr/local/
  unarchive:
    src={{ prometheus_url }}
    dest=/usr/local
    copy=no

- name: create synbolic link
  file: src=/usr/local/{{ prometheus_name }} dest=/usr/local/prometheus state=link

- name: create /usr/local/prometheus/prometheus.yml
  template: src=roles/prometheus_server/templates/prometheus.yml dest=/usr/local/prometheus mode=0775

- name: create /usr/local/data
  file: dest=/usr/local/data state=directory owner={{ supervisor_owner }} group={{ supervisor_group }} mode=0777
